import os


# ============================================================
# ROOT
# ============================================================

ROOT = r"F:\RepoRT-master (2)\Pre_data"


# ============================================================
# Hmol + Mordred + Hcond generated data
#
# Generated by:
# train_test_valid_hmol_mordred_global_molecule.py
# ============================================================

DATA_DIR = os.path.join(
    ROOT,
    "gen_hmol_mordred_molecule_split",
    "np_seed29"
)


# ============================================================
# Continuous features
#
# X =
#
# Hmol
# +
# Mordred
# +
# Column
# +
# Gradient
# +
# Meta
# ============================================================

X_PATH = os.path.join(
    DATA_DIR,
    "X_train.csv"
)


VAL_X_PATH = os.path.join(
    DATA_DIR,
    "X_val.csv"
)


# ============================================================
# USP categorical index
# ============================================================

USP_PATH = os.path.join(
    DATA_DIR,
    "usp_train.csv"
)


VAL_USP_PATH = os.path.join(
    DATA_DIR,
    "usp_val.csv"
)


# ============================================================
# RT
# ============================================================

Y_PATH = os.path.join(
    DATA_DIR,
    "y_train.csv"
)


VAL_Y_PATH = os.path.join(
    DATA_DIR,
    "y_val.csv"
)


# ============================================================
# Feature layout
#
# Created by train_test_valid_hmol_mordred_global_molecule.py
# ============================================================

FEATURE_LAYOUT_PATH = os.path.join(
    DATA_DIR,
    "feature_layout.json"
)


# ============================================================
# Molecule split diagnostics
# ============================================================

TRAIN_SMILES_PATH = os.path.join(
    DATA_DIR,
    "smiles_train.csv"
)

VAL_SMILES_PATH = os.path.join(
    DATA_DIR,
    "smiles_val.csv"
)


# ============================================================
# NEW base-model directory
#
# IMPORTANT:
# Do not overwrite:
#
# base_model/
# base_model_contrastive/
# ============================================================

MODEL_DIR = os.path.join(
    ROOT,
    "base_model_hmol_mordred_molecule_split"
)


os.makedirs(
    MODEL_DIR,
    exist_ok=True
)