# ============================================================
# train_test_valid_hmol_mordred_global_molecule.py
#
# Hybrid molecular representation:
#
#   Hmol (contrastive GIN pretrained on ALL molecules)
#   +
#   Mordred descriptors
#   +
#   Column vector
#   +
#   Gradient vector
#   +
#   Meta vector
#
# USP code remains a separate categorical input.
#
# IMPORTANT CHANGE
# ----------------
# This script no longer reuses the OLD independently generated
# per-dataset random split.
#
# It reuses:
#
#   target/<dataset>/
#       split_index_molecule/np_seed29/
#           train_index.csv
#           val_index.csv
#           test_index.csv
#
# These files are generated by:
#
#   train_test_valid_global_molecule.py
#
# Thus:
#   the same canonical molecule is ALWAYS in the same split
#   across all LC datasets.
#
# IMPORTANT INTERPRETATION
# ------------------------
# GIN pretraining is still unchanged and may use ALL molecules.
# Therefore this is:
#
#   molecule-disjoint supervised RT split
#   + transductive molecular pretraining
#
# It is NOT a strict "test molecules never seen in pretraining"
# experiment.
#
# Output:
#
# Pre_data/
#     gen_hmol_mordred_molecule_split/
#         np_seed29/
#             X_train.csv
#             y_train.csv
#             usp_train.csv
#             X_val.csv
#             y_val.csv
#             usp_val.csv
#             smiles_train.csv
#             smiles_val.csv
#             feature_layout.json
#             processed_datasets.csv
#
#             <dataset_id>/
#                 X_train.csv
#                 y_train.csv
#                 usp_train.csv
#                 X_val.csv
#                 y_val.csv
#                 usp_val.csv
#                 X_test.csv
#                 y_test.csv
#                 usp_test.csv
#                 smiles_train.csv
#                 smiles_val.csv
#                 smiles_test.csv
# ============================================================

import os
import json

import numpy as np
import pandas as pd
import torch

from rdkit import Chem


# ============================================================
# 1. Paths
# ============================================================

ROOT = r"F:\RepoRT-master (2)\Pre_data"

TARGET_DIR = os.path.join(
    ROOT,
    "target"
)

GEN_DIR = os.path.join(
    ROOT,
    "gen_hmol_mordred_molecule_split"
)

GLOBAL_SPLIT_DIR = os.path.join(
    TARGET_DIR,
    "global_molecule_split"
)

# ------------------------------------------------------------
# Keep your existing ALL-molecule pretrained Hmol.
# If you later use scaffold-weighted pretraining, only change
# this path.
# ------------------------------------------------------------
HMOL_PATH = (
    r"F:\RepoRT-master (2)"
    r"\Contrast_learning"
    r"\outputs"
    r"\hmol_embeddings.csv"
)

COL_VEC_DIR = os.path.join(
    ROOT,
    "processed",
    "column_name_vector"
)

GRAD_VEC_DIR = os.path.join(
    ROOT,
    "processed",
    "gradient_vector"
)

META_VEC_DIR = os.path.join(
    ROOT,
    "processed",
    "meta_vector"
)

USP_MAP_PATH = os.path.join(
    ROOT,
    "processed",
    "usp_embedding.pth"
)

USP_DIR = os.path.join(
    ROOT,
    "origin",
    "original_columns_usp_code"
)

SEEDS = [29]


# ============================================================
# 2. Utilities
# ============================================================

def safe_mkdir(
    path
):
    os.makedirs(
        path,
        exist_ok=True
    )


def canonicalize_smiles(
    smi
):
    if pd.isna(
        smi
    ):
        return None

    try:
        mol = Chem.MolFromSmiles(
            str(
                smi
            )
        )

        if mol is None:
            return None

        return Chem.MolToSmiles(
            mol,
            canonical=True,
            isomericSmiles=True
        )

    except Exception:
        return None


def load_index_file(
    path
):
    if not os.path.exists(
        path
    ):
        raise FileNotFoundError(
            path
        )

    if os.path.getsize(
        path
    ) == 0:
        return np.array(
            [],
            dtype=int
        )

    return np.loadtxt(
        path,
        delimiter=",",
        ndmin=1
    ).astype(
        int
    )


def save_vector(
    path,
    arr,
    fmt=None
):
    arr = np.asarray(
        arr
    )

    if fmt is None:
        np.savetxt(
            path,
            arr,
            delimiter=","
        )

    else:
        np.savetxt(
            path,
            arr,
            delimiter=",",
            fmt=fmt
        )


def save_matrix(
    path,
    arr
):
    np.savetxt(
        path,
        np.asarray(
            arr
        ),
        delimiter=","
    )


# ============================================================
# 3. Load Hmol
# ============================================================

print(
    "=" * 78
)

print(
    "Loading all-molecule contrastive Hmol"
)

print(
    "=" * 78
)

print(
    "Hmol file:",
    HMOL_PATH
)

if not os.path.exists(
    HMOL_PATH
):
    raise FileNotFoundError(
        f"Hmol file does not exist:\n"
        f"{HMOL_PATH}"
    )

hmol_df = pd.read_csv(
    HMOL_PATH
)

if (
    "canonical_smiles"
    not in hmol_df.columns
):
    raise ValueError(
        "hmol_embeddings.csv does not contain "
        "'canonical_smiles'."
    )

hmol_cols = [
    c
    for c in hmol_df.columns
    if c.startswith(
        "Hmol_"
    )
]

if len(
    hmol_cols
) == 0:
    raise ValueError(
        "No Hmol_xxx columns were found."
    )

print(
    f"Hmol dimension: "
    f"{len(hmol_cols)}"
)

# Canonicalize Hmol table again.
hmol_df[
    "smiles_key"
] = (
    hmol_df[
        "canonical_smiles"
    ]
    .apply(
        canonicalize_smiles
    )
)

invalid_hmol = (
    hmol_df[
        "smiles_key"
    ]
    .isna()
)

if invalid_hmol.any():
    print(
        "[WARNING] Invalid SMILES in Hmol table:"
    )

    print(
        hmol_df.loc[
            invalid_hmol,
            [
                c
                for c in [
                    "mol_id",
                    "canonical_smiles"
                ]
                if c in hmol_df.columns
            ]
        ].head(
            20
        )
    )

duplicate_mask = (
    hmol_df[
        "smiles_key"
    ]
    .duplicated(
        keep=False
    )
)

if duplicate_mask.any():
    print(
        "[WARNING] Duplicate canonical molecules "
        "in Hmol table; keeping first."
    )

hmol_df = (
    hmol_df
    .dropna(
        subset=[
            "smiles_key"
        ]
    )
    .drop_duplicates(
        subset=[
            "smiles_key"
        ],
        keep="first"
    )
    .reset_index(
        drop=True
    )
)

hmol_map = {}

for _, row in hmol_df.iterrows():

    key = row[
        "smiles_key"
    ]

    vector = (
        row[
            hmol_cols
        ]
        .values
        .astype(
            np.float32
        )
    )

    if not np.isfinite(
        vector
    ).all():
        raise RuntimeError(
            f"Hmol contains NaN/Inf for molecule: {key}"
        )

    hmol_map[
        key
    ] = vector

print(
    f"Hmol lookup molecules: "
    f"{len(hmol_map)}"
)


# ============================================================
# 4. Load USP mapping once
# ============================================================

if not os.path.exists(
    USP_MAP_PATH
):
    raise FileNotFoundError(
        USP_MAP_PATH
    )

usp_checkpoint = torch.load(
    USP_MAP_PATH,
    map_location="cpu"
)

if (
    "word2id"
    not in usp_checkpoint
):
    raise KeyError(
        "usp_embedding.pth does not contain 'word2id'."
    )

word2id = usp_checkpoint[
    "word2id"
]

print(
    f"USP classes: "
    f"{len(word2id)}"
)


# ============================================================
# 5. Global split manifest
# ============================================================

def load_global_split(
    seed
):

    path = os.path.join(
        GLOBAL_SPLIT_DIR,
        f"np_seed{seed}",
        "global_molecule_split.csv"
    )

    if not os.path.exists(
        path
    ):
        raise FileNotFoundError(
            "Global molecule split not found.\n"
            "Run train_test_valid_global_molecule.py first:\n"
            f"{path}"
        )

    split_df = pd.read_csv(
        path
    )

    required = {
        "canonical_smiles",
        "split"
    }

    missing = (
        required
        -
        set(
            split_df.columns
        )
    )

    if missing:
        raise ValueError(
            f"global_molecule_split.csv missing: {missing}"
        )

    split_df[
        "canonical_smiles"
    ] = (
        split_df[
            "canonical_smiles"
        ]
        .apply(
            canonicalize_smiles
        )
    )

    if split_df[
        "canonical_smiles"
    ].isna().any():

        raise RuntimeError(
            "Invalid molecule found in global split manifest."
        )

    train_set = set(
        split_df.loc[
            split_df[
                "split"
            ] == "train",
            "canonical_smiles"
        ]
    )

    val_set = set(
        split_df.loc[
            split_df[
                "split"
            ] == "val",
            "canonical_smiles"
        ]
    )

    test_set = set(
        split_df.loc[
            split_df[
                "split"
            ] == "test",
            "canonical_smiles"
        ]
    )

    if (
        train_set & val_set
        or
        train_set & test_set
        or
        val_set & test_set
    ):
        raise RuntimeError(
            "Global molecule split is not disjoint."
        )

    return (
        split_df,
        train_set,
        val_set,
        test_set
    )


# ============================================================
# 6. Build Hmol + Mordred + condition for one dataset
# ============================================================

def build_features(
    dataset_id
):

    dataset_dir = os.path.join(
        TARGET_DIR,
        dataset_id
    )

    # --------------------------------------------------------
    # Reference MACCS table.
    # MACCS descriptors are NOT used here.
    # Only:
    #   column 0 = SMILES
    #   column 1 = RT
    #   row order
    # --------------------------------------------------------
    maccs_path = os.path.join(
        dataset_dir,
        f"{dataset_id}_maccs.csv"
    )

    if not os.path.exists(
        maccs_path
    ):
        raise FileNotFoundError(
            maccs_path
        )

    maccs = pd.read_csv(
        maccs_path,
        header=None
    )

    # --------------------------------------------------------
    # Mordred
    # --------------------------------------------------------
    mordred_path = os.path.join(
        dataset_dir,
        f"{dataset_id}_mordred_std.csv"
    )

    if not os.path.exists(
        mordred_path
    ):
        raise FileNotFoundError(
            mordred_path
        )

    mordred = pd.read_csv(
        mordred_path,
        header=None
    )

    if len(
        maccs
    ) != len(
        mordred
    ):
        raise RuntimeError(
            f"{dataset_id}: row number mismatch.\n"
            f"MACCS rows   = {len(maccs)}\n"
            f"Mordred rows = {len(mordred)}"
        )

    smiles_raw = (
        maccs.iloc[
            :,
            0
        ]
        .astype(str)
        .tolist()
    )

    y = (
        maccs.iloc[
            :,
            1
        ]
        .values
        .astype(
            np.float32
        )
    )

    mordred_smiles_raw = (
        mordred.iloc[
            :,
            0
        ]
        .astype(str)
        .tolist()
    )

    mordred_y = (
        mordred.iloc[
            :,
            1
        ]
        .values
        .astype(
            np.float32
        )
    )

    if not np.allclose(
        y,
        mordred_y,
        rtol=1e-6,
        atol=1e-6
    ):
        raise RuntimeError(
            f"{dataset_id}: RT mismatch between "
            "MACCS and Mordred."
        )

    canonical_smiles = np.asarray(
        [
            canonicalize_smiles(
                smi
            )
            for smi in smiles_raw
        ],
        dtype=object
    )

    mordred_canonical_smiles = np.asarray(
        [
            canonicalize_smiles(
                smi
            )
            for smi in mordred_smiles_raw
        ],
        dtype=object
    )

    for i, (
        smi1,
        smi2
    ) in enumerate(
        zip(
            canonical_smiles,
            mordred_canonical_smiles
        )
    ):

        if smi1 != smi2:
            raise RuntimeError(
                f"{dataset_id}: SMILES mismatch at row {i}\n"
                f"MACCS canonical: {smi1}\n"
                f"Mordred canonical: {smi2}"
            )

    if any(
        smi is None
        for smi in canonical_smiles
    ):
        raise RuntimeError(
            f"{dataset_id}: invalid canonical SMILES remained."
        )

    # --------------------------------------------------------
    # Hmol lookup
    # --------------------------------------------------------
    missing = [
        smi
        for smi in canonical_smiles
        if smi not in hmol_map
    ]

    if missing:
        print(
            f"[ERROR] {dataset_id}: "
            f"{len(missing)} molecules have no Hmol."
        )

        print(
            "First 10 missing:"
        )

        print(
            missing[
                :10
            ]
        )

        raise RuntimeError(
            f"{dataset_id}: Hmol coverage != 100%."
        )

    X_hmol = np.vstack(
        [
            hmol_map[
                smi
            ]
            for smi in canonical_smiles
        ]
    ).astype(
        np.float32
    )

    # --------------------------------------------------------
    # Mordred descriptors
    # column 2... = descriptor values
    # --------------------------------------------------------
    X_mordred = (
        mordred.iloc[
            :,
            2:
        ]
        .values
        .astype(
            np.float32
        )
    )

    if not np.isfinite(
        X_mordred
    ).all():
        bad = int(
            np.sum(
                ~np.isfinite(
                    X_mordred
                )
            )
        )

        raise RuntimeError(
            f"{dataset_id}: Mordred contains "
            f"{bad} NaN/Inf values."
        )

    n = len(
        y
    )

    if X_hmol.shape[
        0
    ] != n:
        raise RuntimeError(
            f"{dataset_id}: Hmol rows mismatch."
        )

    if X_mordred.shape[
        0
    ] != n:
        raise RuntimeError(
            f"{dataset_id}: Mordred rows mismatch."
        )

    # --------------------------------------------------------
    # Column
    # --------------------------------------------------------
    col_path = os.path.join(
        COL_VEC_DIR,
        f"{dataset_id}.csv"
    )

    if not os.path.exists(
        col_path
    ):
        raise FileNotFoundError(
            col_path
        )

    col = np.loadtxt(
        col_path,
        delimiter=","
    )

    col = (
        np.atleast_1d(
            col
        )
        .astype(
            np.float32
        )
        .reshape(
            -1
        )
    )

    X_col = np.tile(
        col.reshape(
            1,
            -1
        ),
        (
            n,
            1
        )
    )

    # --------------------------------------------------------
    # Gradient
    # --------------------------------------------------------
    grad_path = os.path.join(
        GRAD_VEC_DIR,
        f"{dataset_id}_gradient.csv"
    )

    if not os.path.exists(
        grad_path
    ):
        raise FileNotFoundError(
            grad_path
        )

    grad = np.loadtxt(
        grad_path,
        delimiter=","
    )

    grad = (
        np.atleast_1d(
            grad
        )
        .astype(
            np.float32
        )
        .reshape(
            -1
        )
    )

    X_grad = np.tile(
        grad.reshape(
            1,
            -1
        ),
        (
            n,
            1
        )
    )

    # --------------------------------------------------------
    # Meta
    # --------------------------------------------------------
    meta_path = os.path.join(
        META_VEC_DIR,
        f"{dataset_id}.csv"
    )

    if not os.path.exists(
        meta_path
    ):
        raise FileNotFoundError(
            meta_path
        )

    meta_df = pd.read_csv(
        meta_path
    )

    if len(
        meta_df
    ) == 0:
        raise RuntimeError(
            f"Empty meta file:\n"
            f"{meta_path}"
        )

    meta = (
        meta_df.iloc[
            0
        ]
        .values
        .astype(
            np.float32
        )
        .reshape(
            -1
        )
    )

    X_meta = np.tile(
        meta.reshape(
            1,
            -1
        ),
        (
            n,
            1
        )
    )

    # --------------------------------------------------------
    # Final continuous feature matrix
    # --------------------------------------------------------
    X = np.hstack(
        [
            X_hmol,
            X_mordred,
            X_col,
            X_grad,
            X_meta
        ]
    ).astype(
        np.float32
    )

    if not np.isfinite(
        X
    ).all():
        bad = int(
            np.sum(
                ~np.isfinite(
                    X
                )
            )
        )

        raise RuntimeError(
            f"{dataset_id}: final X contains "
            f"{bad} NaN/Inf values."
        )

    # --------------------------------------------------------
    # USP
    # --------------------------------------------------------
    usp_path = os.path.join(
        USP_DIR,
        f"{dataset_id}.txt"
    )

    if not os.path.exists(
        usp_path
    ):
        raise FileNotFoundError(
            usp_path
        )

    with open(
        usp_path,
        "r",
        encoding="utf-8"
    ) as f:

        usp = (
            f.readline()
            .strip()
        )

    if usp not in word2id:
        raise KeyError(
            f"{dataset_id}: USP '{usp}' "
            "not found in word2id."
        )

    usp_id = int(
        word2id[
            usp
        ]
    )

    usp_index = np.full(
        shape=n,
        fill_value=usp_id,
        dtype=np.int64
    )

    feature_layout = {
        "hmol_dim":
            int(
                X_hmol.shape[
                    1
                ]
            ),

        "mordred_dim":
            int(
                X_mordred.shape[
                    1
                ]
            ),

        "column_dim":
            int(
                X_col.shape[
                    1
                ]
            ),

        "gradient_dim":
            int(
                X_grad.shape[
                    1
                ]
            ),

        "meta_dim":
            int(
                X_meta.shape[
                    1
                ]
            ),

        "total_dim":
            int(
                X.shape[
                    1
                ]
            )
    }

    print(
        f"  Hmol       : {X_hmol.shape}"
    )

    print(
        f"  Mordred    : {X_mordred.shape}"
    )

    print(
        f"  Column     : {X_col.shape}"
    )

    print(
        f"  Gradient   : {X_grad.shape}"
    )

    print(
        f"  Meta       : {X_meta.shape}"
    )

    print(
        f"  Final X    : {X.shape}"
    )

    return (
        X,
        y,
        usp_index,
        canonical_smiles,
        feature_layout
    )


# ============================================================
# 7. Generate data using molecule-disjoint split
# ============================================================

def generate():

    dataset_ids = sorted(
        d
        for d in os.listdir(
            TARGET_DIR
        )
        if (
            os.path.isdir(
                os.path.join(
                    TARGET_DIR,
                    d
                )
            )
            and
            d != "global_molecule_split"
        )
    )

    print(
        "\n" + "=" * 78
    )

    print(
        f"Found {len(dataset_ids)} target dataset directories."
    )

    print(
        "=" * 78
    )

    for seed in SEEDS:

        (
            global_split_df,
            expected_train_molecules,
            expected_val_molecules,
            expected_test_molecules
        ) = load_global_split(
            seed
        )

        split_lookup = dict(
            zip(
                global_split_df[
                    "canonical_smiles"
                ],
                global_split_df[
                    "split"
                ]
            )
        )

        X_train_all = []
        y_train_all = []
        usp_train_all = []
        smiles_train_all = []

        X_val_all = []
        y_val_all = []
        usp_val_all = []
        smiles_val_all = []

        feature_layout = None

        processed_datasets = []

        per_dataset_summary = []

        for dataset_id in dataset_ids:

            maccs_path = os.path.join(
                TARGET_DIR,
                dataset_id,
                f"{dataset_id}_maccs.csv"
            )

            mordred_path = os.path.join(
                TARGET_DIR,
                dataset_id,
                f"{dataset_id}_mordred_std.csv"
            )

            if not os.path.exists(
                maccs_path
            ):
                continue

            if not os.path.exists(
                mordred_path
            ):
                print(
                    f"[SKIP] {dataset_id}: "
                    "missing Mordred file."
                )
                continue

            print(
                "\n" + "-" * 78
            )

            print(
                f"Dataset: {dataset_id}"
            )

            (
                X,
                y,
                usp_index,
                smiles,
                dims
            ) = build_features(
                dataset_id
            )

            # ------------------------------------------------
            # Feature dimension consistency
            # ------------------------------------------------
            if feature_layout is None:
                feature_layout = dims

            else:
                if (
                    dims[
                        "total_dim"
                    ]
                    !=
                    feature_layout[
                        "total_dim"
                    ]
                ):
                    raise RuntimeError(
                        f"{dataset_id}: total feature "
                        "dimension differs.\n"
                        f"Current  = {dims}\n"
                        f"Expected = {feature_layout}"
                    )

                if (
                    dims[
                        "mordred_dim"
                    ]
                    !=
                    feature_layout[
                        "mordred_dim"
                    ]
                ):
                    raise RuntimeError(
                        f"{dataset_id}: Mordred dimension differs."
                    )

            # ------------------------------------------------
            # Load NEW global-molecule-derived indices.
            # ------------------------------------------------
            split_dir = os.path.join(
                TARGET_DIR,
                dataset_id,
                "split_index_molecule",
                f"np_seed{seed}"
            )

            tr = load_index_file(
                os.path.join(
                    split_dir,
                    "train_index.csv"
                )
            )

            va = load_index_file(
                os.path.join(
                    split_dir,
                    "val_index.csv"
                )
            )

            te = load_index_file(
                os.path.join(
                    split_dir,
                    "test_index.csv"
                )
            )

            # ------------------------------------------------
            # Index safety
            # ------------------------------------------------
            all_idx = np.concatenate(
                [
                    tr,
                    va,
                    te
                ]
            )

            if len(
                all_idx
            ) != len(
                X
            ):
                raise RuntimeError(
                    f"{dataset_id}: split indices do not "
                    "cover all rows exactly once.\n"
                    f"rows={len(X)}, "
                    f"indices={len(all_idx)}"
                )

            if len(
                np.unique(
                    all_idx
                )
            ) != len(
                all_idx
            ):
                raise RuntimeError(
                    f"{dataset_id}: duplicated row indices "
                    "across splits."
                )

            if len(
                all_idx
            ) > 0:

                if (
                    int(
                        np.min(
                            all_idx
                        )
                    ) < 0
                    or
                    int(
                        np.max(
                            all_idx
                        )
                    ) >= len(
                        X
                    )
                ):
                    raise RuntimeError(
                        f"{dataset_id}: split index out of range."
                    )

            # ------------------------------------------------
            # Verify each row agrees with global split manifest.
            # ------------------------------------------------
            for idx in tr:

                smi = smiles[
                    idx
                ]

                if split_lookup.get(
                    smi
                ) != "train":
                    raise RuntimeError(
                        f"{dataset_id}: row {idx} "
                        "does not match global train assignment."
                    )

            for idx in va:

                smi = smiles[
                    idx
                ]

                if split_lookup.get(
                    smi
                ) != "val":
                    raise RuntimeError(
                        f"{dataset_id}: row {idx} "
                        "does not match global val assignment."
                    )

            for idx in te:

                smi = smiles[
                    idx
                ]

                if split_lookup.get(
                    smi
                ) != "test":
                    raise RuntimeError(
                        f"{dataset_id}: row {idx} "
                        "does not match global test assignment."
                    )

            # ------------------------------------------------
            # Slice
            # ------------------------------------------------
            X_tr = X[
                tr
            ]

            y_tr = y[
                tr
            ]

            usp_tr = usp_index[
                tr
            ]

            smiles_tr = smiles[
                tr
            ]

            X_va = X[
                va
            ]

            y_va = y[
                va
            ]

            usp_va = usp_index[
                va
            ]

            smiles_va = smiles[
                va
            ]

            X_te = X[
                te
            ]

            y_te = y[
                te
            ]

            usp_te = usp_index[
                te
            ]

            smiles_te = smiles[
                te
            ]

            # ------------------------------------------------
            # Local molecule-disjoint assertion
            # ------------------------------------------------
            train_set = set(
                smiles_tr.tolist()
            )

            val_set = set(
                smiles_va.tolist()
            )

            test_set = set(
                smiles_te.tolist()
            )

            if (
                train_set & val_set
                or
                train_set & test_set
                or
                val_set & test_set
            ):
                raise RuntimeError(
                    f"{dataset_id}: local molecule overlap."
                )

            # ------------------------------------------------
            # Save dataset-specific output
            # ------------------------------------------------
            out_dir = os.path.join(
                GEN_DIR,
                f"np_seed{seed}",
                dataset_id
            )

            safe_mkdir(
                out_dir
            )

            save_matrix(
                os.path.join(
                    out_dir,
                    "X_train.csv"
                ),
                X_tr
            )

            save_vector(
                os.path.join(
                    out_dir,
                    "y_train.csv"
                ),
                y_tr
            )

            save_vector(
                os.path.join(
                    out_dir,
                    "usp_train.csv"
                ),
                usp_tr,
                fmt="%d"
            )

            save_matrix(
                os.path.join(
                    out_dir,
                    "X_val.csv"
                ),
                X_va
            )

            save_vector(
                os.path.join(
                    out_dir,
                    "y_val.csv"
                ),
                y_va
            )

            save_vector(
                os.path.join(
                    out_dir,
                    "usp_val.csv"
                ),
                usp_va,
                fmt="%d"
            )

            save_matrix(
                os.path.join(
                    out_dir,
                    "X_test.csv"
                ),
                X_te
            )

            save_vector(
                os.path.join(
                    out_dir,
                    "y_test.csv"
                ),
                y_te
            )

            save_vector(
                os.path.join(
                    out_dir,
                    "usp_test.csv"
                ),
                usp_te,
                fmt="%d"
            )

            pd.DataFrame(
                {
                    "canonical_smiles":
                        smiles_tr
                }
            ).to_csv(
                os.path.join(
                    out_dir,
                    "smiles_train.csv"
                ),
                index=False
            )

            pd.DataFrame(
                {
                    "canonical_smiles":
                        smiles_va
                }
            ).to_csv(
                os.path.join(
                    out_dir,
                    "smiles_val.csv"
                ),
                index=False
            )

            pd.DataFrame(
                {
                    "canonical_smiles":
                        smiles_te
                }
            ).to_csv(
                os.path.join(
                    out_dir,
                    "smiles_test.csv"
                ),
                index=False
            )

            # ------------------------------------------------
            # Global base-model train / val pools
            # ------------------------------------------------
            if len(
                tr
            ) > 0:

                X_train_all.append(
                    X_tr
                )

                y_train_all.append(
                    y_tr
                )

                usp_train_all.append(
                    usp_tr
                )

                smiles_train_all.append(
                    smiles_tr
                )

            if len(
                va
            ) > 0:

                X_val_all.append(
                    X_va
                )

                y_val_all.append(
                    y_va
                )

                usp_val_all.append(
                    usp_va
                )

                smiles_val_all.append(
                    smiles_va
                )

            processed_datasets.append(
                dataset_id
            )

            per_dataset_summary.append(
                {
                    "dataset_id":
                        dataset_id,

                    "train_rows":
                        len(
                            tr
                        ),

                    "val_rows":
                        len(
                            va
                        ),

                    "test_rows":
                        len(
                            te
                        ),

                    "train_unique_molecules":
                        len(
                            train_set
                        ),

                    "val_unique_molecules":
                        len(
                            val_set
                        ),

                    "test_unique_molecules":
                        len(
                            test_set
                        )
                }
            )

            print(
                f"  train={len(tr)}, "
                f"val={len(va)}, "
                f"test={len(te)}, "
                f"feature_dim={X.shape[1]}"
            )

        # ----------------------------------------------------
        # Merge global train / validation pools
        # ----------------------------------------------------
        if not X_train_all:
            raise RuntimeError(
                "No global training rows were generated."
            )

        if not X_val_all:
            raise RuntimeError(
                "No global validation rows were generated."
            )

        X_train_all = np.vstack(
            X_train_all
        )

        y_train_all = np.concatenate(
            y_train_all
        )

        usp_train_all = np.concatenate(
            usp_train_all
        )

        smiles_train_all = np.concatenate(
            smiles_train_all
        )

        X_val_all = np.vstack(
            X_val_all
        )

        y_val_all = np.concatenate(
            y_val_all
        )

        usp_val_all = np.concatenate(
            usp_val_all
        )

        smiles_val_all = np.concatenate(
            smiles_val_all
        )

        # ----------------------------------------------------
        # Global molecule-disjoint check after merging all
        # datasets.
        #
        # Repeated train molecules across datasets are allowed.
        # What is forbidden:
        #       same molecule in different split labels.
        # ----------------------------------------------------
        observed_train_set = set(
            smiles_train_all.tolist()
        )

        observed_val_set = set(
            smiles_val_all.tolist()
        )

        if observed_train_set & observed_val_set:
            overlap = list(
                observed_train_set
                &
                observed_val_set
            )[
                :20
            ]

            raise RuntimeError(
                "GLOBAL train/val molecule overlap.\n"
                f"Examples: {overlap}"
            )

        # Every observed train molecule must belong to global train.
        if not observed_train_set.issubset(
            expected_train_molecules
        ):
            raise RuntimeError(
                "Observed train molecules do not match "
                "global split manifest."
            )

        if not observed_val_set.issubset(
            expected_val_molecules
        ):
            raise RuntimeError(
                "Observed validation molecules do not match "
                "global split manifest."
            )

        # ----------------------------------------------------
        # Shuffle measurement rows only after assignment.
        # ----------------------------------------------------
        rng = np.random.RandomState(
            seed
        )

        tr_shuffle = rng.permutation(
            len(
                X_train_all
            )
        )

        va_shuffle = rng.permutation(
            len(
                X_val_all
            )
        )

        X_train_all = X_train_all[
            tr_shuffle
        ]

        y_train_all = y_train_all[
            tr_shuffle
        ]

        usp_train_all = usp_train_all[
            tr_shuffle
        ]

        smiles_train_all = smiles_train_all[
            tr_shuffle
        ]

        X_val_all = X_val_all[
            va_shuffle
        ]

        y_val_all = y_val_all[
            va_shuffle
        ]

        usp_val_all = usp_val_all[
            va_shuffle
        ]

        smiles_val_all = smiles_val_all[
            va_shuffle
        ]

        # ----------------------------------------------------
        # Save global pool
        # ----------------------------------------------------
        global_dir = os.path.join(
            GEN_DIR,
            f"np_seed{seed}"
        )

        safe_mkdir(
            global_dir
        )

        save_matrix(
            os.path.join(
                global_dir,
                "X_train.csv"
            ),
            X_train_all
        )

        save_vector(
            os.path.join(
                global_dir,
                "y_train.csv"
            ),
            y_train_all
        )

        save_vector(
            os.path.join(
                global_dir,
                "usp_train.csv"
            ),
            usp_train_all,
            fmt="%d"
        )

        save_matrix(
            os.path.join(
                global_dir,
                "X_val.csv"
            ),
            X_val_all
        )

        save_vector(
            os.path.join(
                global_dir,
                "y_val.csv"
            ),
            y_val_all
        )

        save_vector(
            os.path.join(
                global_dir,
                "usp_val.csv"
            ),
            usp_val_all,
            fmt="%d"
        )

        pd.DataFrame(
            {
                "canonical_smiles":
                    smiles_train_all
            }
        ).to_csv(
            os.path.join(
                global_dir,
                "smiles_train.csv"
            ),
            index=False
        )

        pd.DataFrame(
            {
                "canonical_smiles":
                    smiles_val_all
            }
        ).to_csv(
            os.path.join(
                global_dir,
                "smiles_val.csv"
            ),
            index=False
        )

        with open(
            os.path.join(
                global_dir,
                "feature_layout.json"
            ),
            "w",
            encoding="utf-8"
        ) as f:

            json.dump(
                feature_layout,
                f,
                indent=2,
                ensure_ascii=False
            )

        pd.DataFrame(
            {
                "dataset_id":
                    processed_datasets
            }
        ).to_csv(
            os.path.join(
                global_dir,
                "processed_datasets.csv"
            ),
            index=False
        )

        pd.DataFrame(
            per_dataset_summary
        ).to_csv(
            os.path.join(
                global_dir,
                "dataset_split_summary.csv"
            ),
            index=False
        )

        # ----------------------------------------------------
        # Save experiment definition for reproducibility.
        # ----------------------------------------------------
        experiment_info = {
            "seed":
                seed,

            "split_type":
                "global_canonical_molecule_disjoint",

            "gin_pretraining":
                "all_molecules_transductive",

            "hmol_path":
                HMOL_PATH,

            "global_train_unique_molecules":
                len(
                    expected_train_molecules
                ),

            "global_val_unique_molecules":
                len(
                    expected_val_molecules
                ),

            "global_test_unique_molecules":
                len(
                    expected_test_molecules
                ),

            "global_train_measurement_rows":
                int(
                    len(
                        X_train_all
                    )
                ),

            "global_val_measurement_rows":
                int(
                    len(
                        X_val_all
                    )
                )
        }

        with open(
            os.path.join(
                global_dir,
                "experiment_info.json"
            ),
            "w",
            encoding="utf-8"
        ) as f:

            json.dump(
                experiment_info,
                f,
                indent=2,
                ensure_ascii=False
            )

        print(
            "\n" + "=" * 78
        )

        print(
            "Hmol + Mordred + condition generation finished"
        )

        print(
            "=" * 78
        )

        print(
            f"Datasets processed: "
            f"{len(processed_datasets)}"
        )

        print(
            f"Final train: "
            f"{X_train_all.shape}"
        )

        print(
            f"Final val: "
            f"{X_val_all.shape}"
        )

        print(
            f"Observed train unique molecules: "
            f"{len(observed_train_set)}"
        )

        print(
            f"Observed val unique molecules: "
            f"{len(observed_val_set)}"
        )

        print(
            "Global train/val molecule overlap: 0"
        )

        print(
            "\nFeature layout:"
        )

        print(
            json.dumps(
                feature_layout,
                indent=2
            )
        )

        print(
            "\nOutput directory:"
        )

        print(
            global_dir
        )


# ============================================================
# 8. Main
# ============================================================

if __name__ == "__main__":

    generate()

    print(
        "\nAll finished."
    )
